// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package raft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry struct {
	Index                uint64   `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Term                 uint64   `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	Command              []byte   `protobuf:"bytes,3,opt,name=Command,proto3" json:"Command,omitempty"`
	CommandType          uint32   `protobuf:"varint,4,opt,name=CommandType,proto3" json:"CommandType,omitempty"`
	CommandId            string   `protobuf:"bytes,5,opt,name=CommandId,proto3" json:"CommandId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Entry) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Entry) GetCommandType() uint32 {
	if m != nil {
		return m.CommandType
	}
	return 0
}

func (m *Entry) GetCommandId() string {
	if m != nil {
		return m.CommandId
	}
	return ""
}

type RequestVoteRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	CandidateId          string   `protobuf:"bytes,2,opt,name=CandidateId,proto3" json:"CandidateId,omitempty"`
	LastLogIndex         uint64   `protobuf:"varint,3,opt,name=LastLogIndex,proto3" json:"LastLogIndex,omitempty"`
	LastLogTerm          uint64   `protobuf:"varint,4,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteRequest) Reset()         { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()    {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{1}
}

func (m *RequestVoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRequest.Unmarshal(m, b)
}
func (m *RequestVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRequest.Marshal(b, m, deterministic)
}
func (m *RequestVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRequest.Merge(m, src)
}
func (m *RequestVoteRequest) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRequest.Size(m)
}
func (m *RequestVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRequest proto.InternalMessageInfo

func (m *RequestVoteRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

func (m *RequestVoteRequest) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=VoteGranted,proto3" json:"VoteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteResponse) Reset()         { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()    {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{2}
}

func (m *RequestVoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteResponse.Unmarshal(m, b)
}
func (m *RequestVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteResponse.Marshal(b, m, deterministic)
}
func (m *RequestVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteResponse.Merge(m, src)
}
func (m *RequestVoteResponse) XXX_Size() int {
	return xxx_messageInfo_RequestVoteResponse.Size(m)
}
func (m *RequestVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteResponse proto.InternalMessageInfo

func (m *RequestVoteResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type AppendEntriesRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LeaderId             string   `protobuf:"bytes,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	PrevLogIndex         uint64   `protobuf:"varint,3,opt,name=PrevLogIndex,proto3" json:"PrevLogIndex,omitempty"`
	PrevLogTerm          uint64   `protobuf:"varint,4,opt,name=PrevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	Entries              []*Entry `protobuf:"bytes,5,rep,name=Entries,proto3" json:"Entries,omitempty"`
	LeaderCommit         uint64   `protobuf:"varint,6,opt,name=LeaderCommit,proto3" json:"LeaderCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesRequest) Reset()         { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()    {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{3}
}

func (m *AppendEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRequest.Unmarshal(m, b)
}
func (m *AppendEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRequest.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRequest.Merge(m, src)
}
func (m *AppendEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRequest.Size(m)
}
func (m *AppendEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRequest proto.InternalMessageInfo

func (m *AppendEntriesRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntriesRequest) GetPrevLogIndex() uint64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesRequest) GetLeaderCommit() uint64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResponse) Reset()         { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()    {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{4}
}

func (m *AppendEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResponse.Unmarshal(m, b)
}
func (m *AppendEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResponse.Marshal(b, m, deterministic)
}
func (m *AppendEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResponse.Merge(m, src)
}
func (m *AppendEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResponse.Size(m)
}
func (m *AppendEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResponse proto.InternalMessageInfo

func (m *AppendEntriesResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type InstallSnapshotRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LeaderId             string   `protobuf:"bytes,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	LastIncludedIndex    uint64   `protobuf:"varint,3,opt,name=LastIncludedIndex,proto3" json:"LastIncludedIndex,omitempty"`
	LastIncludedTerm     uint64   `protobuf:"varint,4,opt,name=LastIncludedTerm,proto3" json:"LastIncludedTerm,omitempty"`
	Offset               uint64   `protobuf:"varint,5,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	Done                 bool     `protobuf:"varint,7,opt,name=Done,proto3" json:"Done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSnapshotRequest) Reset()         { *m = InstallSnapshotRequest{} }
func (m *InstallSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotRequest) ProtoMessage()    {}
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{5}
}

func (m *InstallSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSnapshotRequest.Unmarshal(m, b)
}
func (m *InstallSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *InstallSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSnapshotRequest.Merge(m, src)
}
func (m *InstallSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_InstallSnapshotRequest.Size(m)
}
func (m *InstallSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSnapshotRequest proto.InternalMessageInfo

func (m *InstallSnapshotRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *InstallSnapshotRequest) GetLastIncludedIndex() uint64 {
	if m != nil {
		return m.LastIncludedIndex
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLastIncludedTerm() uint64 {
	if m != nil {
		return m.LastIncludedTerm
	}
	return 0
}

func (m *InstallSnapshotRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *InstallSnapshotRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InstallSnapshotRequest) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type InstallSnapshotResponse struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSnapshotResponse) Reset()         { *m = InstallSnapshotResponse{} }
func (m *InstallSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotResponse) ProtoMessage()    {}
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{6}
}

func (m *InstallSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSnapshotResponse.Unmarshal(m, b)
}
func (m *InstallSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSnapshotResponse.Marshal(b, m, deterministic)
}
func (m *InstallSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSnapshotResponse.Merge(m, src)
}
func (m *InstallSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_InstallSnapshotResponse.Size(m)
}
func (m *InstallSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSnapshotResponse proto.InternalMessageInfo

func (m *InstallSnapshotResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type LogStorage struct {
	CurrentTerm          uint64   `protobuf:"varint,1,opt,name=CurrentTerm,proto3" json:"CurrentTerm,omitempty"`
	VotedFor             string   `protobuf:"bytes,2,opt,name=VotedFor,proto3" json:"VotedFor,omitempty"`
	Entries              []*Entry `protobuf:"bytes,3,rep,name=Entries,proto3" json:"Entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogStorage) Reset()         { *m = LogStorage{} }
func (m *LogStorage) String() string { return proto.CompactTextString(m) }
func (*LogStorage) ProtoMessage()    {}
func (*LogStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{7}
}

func (m *LogStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogStorage.Unmarshal(m, b)
}
func (m *LogStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogStorage.Marshal(b, m, deterministic)
}
func (m *LogStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogStorage.Merge(m, src)
}
func (m *LogStorage) XXX_Size() int {
	return xxx_messageInfo_LogStorage.Size(m)
}
func (m *LogStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogStorage.DiscardUnknown(m)
}

var xxx_messageInfo_LogStorage proto.InternalMessageInfo

func (m *LogStorage) GetCurrentTerm() uint64 {
	if m != nil {
		return m.CurrentTerm
	}
	return 0
}

func (m *LogStorage) GetVotedFor() string {
	if m != nil {
		return m.VotedFor
	}
	return ""
}

func (m *LogStorage) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ConfigurationStorage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Peers                []string `protobuf:"bytes,2,rep,name=Peers,proto3" json:"Peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigurationStorage) Reset()         { *m = ConfigurationStorage{} }
func (m *ConfigurationStorage) String() string { return proto.CompactTextString(m) }
func (*ConfigurationStorage) ProtoMessage()    {}
func (*ConfigurationStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{8}
}

func (m *ConfigurationStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationStorage.Unmarshal(m, b)
}
func (m *ConfigurationStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationStorage.Marshal(b, m, deterministic)
}
func (m *ConfigurationStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationStorage.Merge(m, src)
}
func (m *ConfigurationStorage) XXX_Size() int {
	return xxx_messageInfo_ConfigurationStorage.Size(m)
}
func (m *ConfigurationStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationStorage.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationStorage proto.InternalMessageInfo

func (m *ConfigurationStorage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigurationStorage) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "raft.Entry")
	proto.RegisterType((*RequestVoteRequest)(nil), "raft.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "raft.RequestVoteResponse")
	proto.RegisterType((*AppendEntriesRequest)(nil), "raft.AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesResponse)(nil), "raft.AppendEntriesResponse")
	proto.RegisterType((*InstallSnapshotRequest)(nil), "raft.InstallSnapshotRequest")
	proto.RegisterType((*InstallSnapshotResponse)(nil), "raft.InstallSnapshotResponse")
	proto.RegisterType((*LogStorage)(nil), "raft.LogStorage")
	proto.RegisterType((*ConfigurationStorage)(nil), "raft.ConfigurationStorage")
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_b042552c306ae59b) }

var fileDescriptor_b042552c306ae59b = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0xd5, 0x92, 0x4d, 0xd2, 0x4c, 0x82, 0x04, 0x26, 0x14, 0x0b, 0x71, 0x58, 0x59, 0x42, 0x5a,
	0x21, 0xe8, 0x01, 0x7e, 0x00, 0x54, 0x0a, 0x8a, 0x88, 0xa0, 0x72, 0x2a, 0xee, 0x26, 0x9e, 0x84,
	0x48, 0x89, 0xbd, 0xb5, 0xbd, 0x88, 0x7e, 0x03, 0x17, 0xfe, 0x8e, 0x3b, 0x5f, 0x82, 0x3c, 0xd9,
	0x0d, 0x6e, 0xa3, 0xf4, 0xd0, 0xdb, 0xbc, 0x67, 0xef, 0xce, 0x7b, 0x6f, 0x46, 0x06, 0x70, 0x6a,
	0x11, 0x4e, 0x2a, 0x67, 0x83, 0x65, 0x79, 0xac, 0xc5, 0xaf, 0x0c, 0xba, 0x67, 0x26, 0xb8, 0x2b,
	0x36, 0x86, 0xee, 0xc4, 0x68, 0xfc, 0xc9, 0xb3, 0x22, 0x2b, 0x73, 0xb9, 0x05, 0x8c, 0x41, 0x7e,
	0x81, 0x6e, 0xc3, 0xef, 0x11, 0x49, 0x35, 0xe3, 0xd0, 0x3f, 0xb5, 0x9b, 0x8d, 0x32, 0x9a, 0x77,
	0x8a, 0xac, 0x1c, 0xc9, 0x16, 0xb2, 0x02, 0x86, 0x4d, 0x79, 0x71, 0x55, 0x21, 0xcf, 0x8b, 0xac,
	0xbc, 0x2f, 0x53, 0x8a, 0x3d, 0x83, 0x41, 0x03, 0x27, 0x9a, 0x77, 0x8b, 0xac, 0x1c, 0xc8, 0xff,
	0x84, 0xf8, 0x9d, 0x01, 0x93, 0x78, 0x59, 0xa3, 0x0f, 0x5f, 0x6d, 0xc0, 0xa6, 0xdc, 0x89, 0xc8,
	0x12, 0x11, 0xb1, 0x95, 0x32, 0x7a, 0xa5, 0x55, 0xc0, 0x89, 0x26, 0x7d, 0x03, 0x99, 0x52, 0x4c,
	0xc0, 0x68, 0xaa, 0x7c, 0x98, 0xda, 0xe5, 0xd6, 0x57, 0x87, 0xbe, 0xbe, 0xc6, 0xc5, 0xbf, 0x34,
	0x98, 0x1a, 0xe4, 0x74, 0x25, 0xa5, 0xc4, 0x27, 0x78, 0x74, 0x4d, 0x91, 0xaf, 0xac, 0xf1, 0x78,
	0x48, 0x52, 0xbc, 0xf3, 0xd1, 0x29, 0x13, 0x70, 0x2b, 0xe9, 0x48, 0xa6, 0x94, 0xf8, 0x93, 0xc1,
	0xf8, 0x5d, 0x55, 0xa1, 0xd1, 0x31, 0xf3, 0x15, 0xfa, 0xdb, 0x1c, 0x3e, 0x85, 0xa3, 0x29, 0x2a,
	0x8d, 0x6e, 0x67, 0x6f, 0x87, 0xa3, 0xb7, 0x73, 0x87, 0x3f, 0x6e, 0x7a, 0x4b, 0xb9, 0x28, 0xa7,
	0xc1, 0xa9, 0xb7, 0x84, 0x62, 0xcf, 0xa1, 0xdf, 0xe8, 0xe0, 0xdd, 0xa2, 0x53, 0x0e, 0x5f, 0x0f,
	0x4f, 0x68, 0x41, 0x68, 0x21, 0x64, 0x7b, 0x46, 0x41, 0x52, 0xe3, 0x38, 0xa8, 0x55, 0xe0, 0xbd,
	0x26, 0xc8, 0x84, 0x13, 0x67, 0xf0, 0xf8, 0x86, 0xb1, 0x5b, 0x82, 0xe2, 0xd0, 0x9f, 0xd5, 0xf3,
	0x39, 0x7a, 0xdf, 0x84, 0xd4, 0x42, 0xf1, 0x37, 0x83, 0xe3, 0x89, 0xf1, 0x41, 0xad, 0xd7, 0x33,
	0xa3, 0x2a, 0xff, 0xdd, 0x86, 0xbb, 0x46, 0xf4, 0x12, 0x1e, 0xc6, 0x39, 0x4e, 0xcc, 0x7c, 0x5d,
	0x6b, 0xd4, 0x69, 0x4e, 0xfb, 0x07, 0xec, 0x05, 0x3c, 0x48, 0xc9, 0x24, 0xb1, 0x3d, 0x9e, 0x1d,
	0x43, 0xef, 0xcb, 0x62, 0xe1, 0x31, 0xd0, 0x02, 0xe7, 0xb2, 0x41, 0x51, 0xe1, 0x7b, 0x15, 0x14,
	0xe5, 0x33, 0x92, 0x54, 0x13, 0x67, 0x0d, 0xf2, 0x3e, 0xf9, 0xa4, 0x5a, 0xbc, 0x82, 0x27, 0x7b,
	0x1e, 0x0f, 0xa7, 0x25, 0x2e, 0x01, 0xa6, 0x76, 0x39, 0x0b, 0xd6, 0xa9, 0x25, 0xd2, 0xde, 0xd7,
	0xce, 0xa1, 0x09, 0xc9, 0xc5, 0x94, 0x8a, 0xa1, 0xc4, 0x9d, 0xd3, 0x1f, 0xac, 0x6b, 0x43, 0x69,
	0x71, 0x3a, 0xf1, 0xce, 0xe1, 0x89, 0x8b, 0xb7, 0x30, 0x3e, 0xb5, 0x66, 0xb1, 0x5a, 0xd6, 0x4e,
	0x85, 0x95, 0x35, 0x6d, 0x73, 0x06, 0xf9, 0x67, 0xb5, 0x41, 0xea, 0x3a, 0x90, 0x54, 0xc7, 0x77,
	0xe3, 0x1c, 0xd1, 0xc5, 0x51, 0x76, 0xca, 0x81, 0xdc, 0x82, 0x6f, 0x3d, 0x7a, 0x64, 0xde, 0xfc,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x58, 0xde, 0xea, 0x58, 0x72, 0x04, 0x00, 0x00,
}
