// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetCommand struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCommand) Reset()         { *m = SetCommand{} }
func (m *SetCommand) String() string { return proto.CompactTextString(m) }
func (*SetCommand) ProtoMessage()    {}
func (*SetCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *SetCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCommand.Unmarshal(m, b)
}
func (m *SetCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCommand.Marshal(b, m, deterministic)
}
func (m *SetCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCommand.Merge(m, src)
}
func (m *SetCommand) XXX_Size() int {
	return xxx_messageInfo_SetCommand.Size(m)
}
func (m *SetCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCommand.DiscardUnknown(m)
}

var xxx_messageInfo_SetCommand proto.InternalMessageInfo

func (m *SetCommand) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetCommand) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Request struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Response struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Leader               string   `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Response) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

type Status struct {
	IsLeader             bool     `protobuf:"varint,1,opt,name=IsLeader,proto3" json:"IsLeader,omitempty"`
	Leader               string   `protobuf:"bytes,2,opt,name=Leader,proto3" json:"Leader,omitempty"`
	Node                 string   `protobuf:"bytes,3,opt,name=Node,proto3" json:"Node,omitempty"`
	Peers                []string `protobuf:"bytes,4,rep,name=Peers,proto3" json:"Peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *Status) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *Status) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Status) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*SetCommand)(nil), "node.SetCommand")
	proto.RegisterType((*Request)(nil), "node.Request")
	proto.RegisterType((*Response)(nil), "node.Response")
	proto.RegisterType((*Status)(nil), "node.Status")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x3b, 0xab, 0xc2, 0x40,
	0x10, 0x85, 0xc9, 0xe3, 0xe6, 0xe6, 0x4e, 0x71, 0x91, 0x41, 0x64, 0xb1, 0x0a, 0xa9, 0xac, 0x04,
	0x1f, 0xff, 0xc0, 0x4a, 0x0c, 0x22, 0x1b, 0xb0, 0x5f, 0xd9, 0xb1, 0xc9, 0x63, 0x62, 0x76, 0x53,
	0xf8, 0xef, 0x65, 0x37, 0x41, 0xb0, 0xb3, 0x3b, 0xdf, 0x61, 0x3e, 0x38, 0x0c, 0x40, 0xcb, 0x9a,
	0xd6, 0x5d, 0xcf, 0x96, 0x31, 0x76, 0x39, 0xdf, 0x03, 0x94, 0x64, 0x0f, 0xdc, 0x34, 0xaa, 0xd5,
	0x38, 0x83, 0xe8, 0x44, 0x4f, 0x11, 0x64, 0xc1, 0xea, 0x4f, 0xba, 0x88, 0x73, 0xf8, 0xb9, 0xaa,
	0x7a, 0x20, 0x11, 0xfa, 0x6e, 0x84, 0x7c, 0x03, 0xbf, 0x92, 0x1e, 0x03, 0x19, 0xfb, 0xb5, 0xb2,
	0x85, 0x54, 0x92, 0xe9, 0xb8, 0x35, 0x84, 0xff, 0x10, 0x72, 0xe5, 0x95, 0x54, 0x86, 0x5c, 0xe1,
	0x02, 0x92, 0x9a, 0x94, 0xa6, 0x7e, 0x52, 0x26, 0xca, 0xef, 0x90, 0x94, 0x56, 0xd9, 0xc1, 0xe0,
	0x12, 0xd2, 0xa3, 0x29, 0xc6, 0x9b, 0xd1, 0x7b, 0xb3, 0xb3, 0x8b, 0x0f, 0x7b, 0xea, 0x11, 0xe2,
	0x33, 0x6b, 0x12, 0x91, 0x6f, 0x7d, 0x76, 0xdb, 0x2e, 0x44, 0xbd, 0x11, 0x71, 0x16, 0xb9, 0x6d,
	0x1e, 0x6e, 0x89, 0xff, 0xc8, 0xee, 0x15, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xfc, 0x17, 0x07, 0x1f,
	0x01, 0x00, 0x00,
}
